// Auto-generated by Atraktos. Do not edit by hand.

mod __gen {
    pub use moirai_crdt::bag::aw_bag::AWBagLog;
    pub use moirai_crdt::counter::resettable_counter::Counter;
    pub use moirai_crdt::flag::ew_flag::EWFlag;
    pub use moirai_crdt::list::eg_walker::List;
    pub use moirai_crdt::list::nested_list::ListLog;
    pub use moirai_crdt::option::OptionLog;
    pub use moirai_crdt::register::mv_register::MVRegister;
    pub use moirai_macros::record;
    pub use moirai_macros::union;
    pub use moirai_protocol::state::event_graph::EventGraph;
    pub use moirai_protocol::state::po_log::VecLog;
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum IdentifierType {
    #[default]
    Custom,
    Irdi,
    Iri,
}
__gen::union!(
    Referable = SubmodelElement(SubmodelElement, SubmodelElementLog) | View(View, ViewLog)
);
__gen::record!(
    ReferableFeat { id_short : __gen::EventGraph < __gen::List < char > >, category :
    __gen::EventGraph < __gen::List < char > >, description : __gen::ListLog <
    LangStringLog >, }
);
__gen::union!(
    Identifiable = Asset(Asset, AssetLog)
        | Submodel(Submodel, SubmodelLog)
        | ConceptDescription(ConceptDescription, ConceptDescriptionLog)
);
__gen::record!(
    IdentifiableFeat { referable_feat : ReferableFeatLog, administration :
    __gen::OptionLog < AdministrativeInformationLog >, identification : IdentifierLog, }
);
__gen::union!(
    HasDataSpecification = Asset(Asset, AssetLog)
        | Submodel(Submodel, SubmodelLog)
        | SubmodelElement(SubmodelElement, SubmodelElementLog)
        | ConceptDescription(ConceptDescription, ConceptDescriptionLog)
        | View(View, ViewLog)
);
__gen::record!(HasDataSpecificationFeat {});
__gen::record!(
    AssetAdministrationShell { identifiable_feat : IdentifiableFeatLog,
    has_data_specification_feat : HasDataSpecificationFeatLog, asset_information :
    AssetInformationLog, endpoint : __gen::OptionLog < AASEndpointLog >, }
);
__gen::record!(
    Security { access_control_policy_points : AccessControlPolicyPointsLog, certificate :
    __gen::ListLog < CertificateLog >, }
);
__gen::record!(
    AssetInformation { asset_kind : __gen::VecLog < __gen::MVRegister < AssetKind > >, }
);
__gen::record!(
    Asset { identifiable_feat : IdentifiableFeatLog, has_data_specification_feat :
    HasDataSpecificationFeatLog, kind : __gen::VecLog < __gen::MVRegister < AssetKind >
    >, endpoint : __gen::ListLog < EndpointLog >, }
);
__gen::union!(HasKind = SubmodelElement(SubmodelElement, SubmodelElementLog));
__gen::record!(
    HasKindFeat { kind : __gen::VecLog < __gen::MVRegister < ModelingKind > >, }
);
__gen::union!(
    HasSemantics = SubmodelElement(SubmodelElement, SubmodelElementLog)
        | IdentifierKeyValuePair(IdentifierKeyValuePair, IdentifierKeyValuePairLog)
        | View(View, ViewLog)
);
__gen::record!(HasSemanticsFeat {});
__gen::record!(Submodel {
    identifiable_feat: IdentifiableFeatLog,
    has_data_specification_feat: HasDataSpecificationFeatLog,
    has_kind_feat: HasKindFeatLog,
    has_semantics_feat: HasSemanticsFeatLog,
});
__gen::record!(
    AASEndpoint { address : __gen::EventGraph < __gen::List < char > >, port :
    __gen::VecLog < __gen::Counter < i32 > >, security : __gen::VecLog <
    __gen::MVRegister < SecurityKind > >, }
);
__gen::record!(
    AdministrativeInformation { version : __gen::EventGraph < __gen::List < char > >,
    revision : __gen::EventGraph < __gen::List < char > >, }
);
__gen::record!(
    Identifier { id_type : __gen::VecLog < __gen::MVRegister < IdentifierType > >, id :
    __gen::EventGraph < __gen::List < char > >, }
);
__gen::record!(
    LangString { lang : __gen::VecLog < __gen::MVRegister < LangEnum > >, value :
    __gen::EventGraph < __gen::List < char > >, }
);
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum LangEnum {
    #[default]
    En,
    Ar,
    Cs,
    Da,
    De,
    Es,
    Fr,
    Hi,
    Id,
    It,
    Ja,
    Ko,
    Ml,
    Nl,
    No,
    Pl,
    Pt,
    Ro,
    Ru,
    Sr,
    Sv,
    Th,
    Tr,
    Zh,
}
__gen::record!(Reference {});
__gen::record!(
    Key { r#type : __gen::VecLog < __gen::MVRegister < KeyElements > >, value :
    __gen::EventGraph < __gen::List < char > >, id_type : __gen::VecLog <
    __gen::MVRegister < KeyType > >, }
);
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum KeyElements {
    #[default]
    GlobalReference,
    FragmentReference,
    AccessPermissionRule,
    AnnotatedRelationshipElement,
    BasicEvent,
    Blob,
    Capability,
    ConceptDictionary,
    DataElement,
    File,
    Entity,
    Event,
    MultiLanguageProperty,
    Operation,
    Property,
    Range,
    ReferenceElement,
    RelationshipElement,
    SubmodelElement,
    SubmodelElementCollection,
    View,
    ConceptDescription,
    Asset,
    AssetAdministrationShell,
    Submodel,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum KeyType {
    #[default]
    Custom,
    Irdi,
    Iri,
    IdShort,
    FragmentId,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum ReferableElements {
    #[default]
    AccessPermissionRule,
    AnnotatedRelationshipElement,
    BasicEvent,
    Blob,
    Capability,
    ConceptDictionary,
    DataElement,
    File,
    Entity,
    Event,
    MultiLanguageProperty,
    Operation,
    Property,
    Range,
    ReferenceElement,
    RelationshipElement,
    SubmodelElement,
    SubmodelElementCollection,
    View,
    ConceptDescription,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum IdentifiableElement {
    #[default]
    Asset,
    AssetAdministrationShell,
    ConceptDescription,
    Submodel,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum LocalKeyType {
    #[default]
    IdShort,
    FragmentId,
}
__gen::record!(
    AccessControlPolicyPoints { external_access_control : __gen::VecLog < __gen::EWFlag
    >, external_information_points : __gen::VecLog < __gen::EWFlag >,
    external_policy_decision_points : __gen::VecLog < __gen::EWFlag >,
    external_policy_enforcement_point : __gen::VecLog < __gen::EWFlag >,
    local_access_control : AccessControlLog, }
);
__gen::record!(Certificate {});
__gen::record!(AccessControl {});
__gen::union!(
    SubmodelElement = DataElement(DataElement, DataElementLog)
        | Entity(Entity, EntityLog)
        | RelationshipElement(RelationshipElement, RelationshipElementLog)
        | Operation(Operation, OperationLog)
        | SubmodelElementCollection(SubmodelElementCollection, SubmodelElementCollectionLog)
        | Event(Event, EventLog)
        | Capability(Capability, CapabilityLog)
);
__gen::record!(
    SubmodelElementFeat { has_data_specification_feat : HasDataSpecificationFeatLog,
    referable_feat : ReferableFeatLog, has_kind_feat : HasKindFeatLog, has_semantics_feat
    : HasSemanticsFeatLog, is_dynamic : __gen::VecLog < __gen::EWFlag >, end_point :
    __gen::OptionLog < EndpointLog >, node_id : __gen::OptionLog < NodeIdLog >, }
);
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum ModelingKind {
    #[default]
    Template,
    Instance,
}
__gen::record!(
    Endpoint { address : __gen::EventGraph < __gen::List < char > >, protocol :
    __gen::VecLog < __gen::MVRegister < ProtocolKind > >, name : __gen::EventGraph <
    __gen::List < char > >, }
);
__gen::record!(
    NodeId { name_space_index : __gen::VecLog < __gen::Counter < i32 > >, identifier :
    __gen::EventGraph < __gen::List < char > >, id_type : __gen::VecLog <
    __gen::MVRegister < IdType > >, }
);
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum ProtocolKind {
    #[default]
    Http,
    Mqtt,
    Opcua,
    CoAp,
    Ros,
    WebSocket,
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum IdType {
    #[default]
    String,
    Integer,
    Long,
    ByteArray,
    Uuid,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum AssetKind {
    #[default]
    Type,
    Instance,
}
__gen::record!(
    IdentifierKeyValuePair { has_semantics_feat : HasSemanticsFeatLog, key :
    __gen::EventGraph < __gen::List < char > >, value : __gen::EventGraph < __gen::List <
    char > >, }
);
__gen::union!(
    DataElement = Property(Property, PropertyLog)
        | ReferenceElement(ReferenceElement, ReferenceElementLog)
        | Range(Range, RangeLog)
        | MultiLanguageProperty(MultiLanguageProperty, MultiLanguagePropertyLog)
);
__gen::record!(DataElementFeat {
    submodel_element_feat: SubmodelElementFeatLog,
});
__gen::record!(
    File { data_element_feat : DataElementFeatLog, path : __gen::EventGraph < __gen::List
    < char > >, mime_type : __gen::VecLog < __gen::MVRegister < MimeType > >, }
);
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum MimeType {
    #[default]
    Applicationjson,
    Applicationxls,
    Applicationpdf,
    Applicationzip,
    Applicationxml,
    Applicationiges,
    Applicationstep,
    Imagepng,
    Imagebmp,
    Imagejpeg,
    Imagegif,
    Textxml,
    Textplain,
    Texthtml,
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum SecurityKind {
    #[default]
    None,
    Https,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum EntityType {
    #[default]
    CoManagedEntity,
    SelfManagedEntity,
}
__gen::record!(
    Entity { submodel_element_feat : SubmodelElementFeatLog, entity_type : __gen::VecLog
    < __gen::MVRegister < EntityType > >, }
);
__gen::record!(RelationshipElement {
    submodel_element_feat: SubmodelElementFeatLog,
});
__gen::record!(Operation {
    submodel_element_feat: SubmodelElementFeatLog,
});
__gen::record!(
    SubmodelElementCollection { submodel_element_feat : SubmodelElementFeatLog, ordered :
    __gen::VecLog < __gen::EWFlag >, allow_duplicates : __gen::VecLog < __gen::EWFlag >,
    }
);
__gen::record!(Property {
    data_element_feat: DataElementFeatLog,
});
__gen::record!(ReferenceElement {
    data_element_feat: DataElementFeatLog,
});
__gen::union!(Event = BasicEvent(BasicEvent, BasicEventLog));
__gen::record!(EventFeat {
    submodel_element_feat: SubmodelElementFeatLog,
});
__gen::record!(BasicEvent {
    event_feat: EventFeatLog,
});
__gen::record!(
    Range { data_element_feat : DataElementFeatLog, min : __gen::VecLog < __gen::Counter
    < i32 > >, max : __gen::VecLog < __gen::Counter < i32 > >, }
);
__gen::record!(Capability {
    submodel_element_feat: SubmodelElementFeatLog,
});
__gen::record!(ConceptDescription {
    identifiable_feat: IdentifiableFeatLog,
    has_data_specification_feat: HasDataSpecificationFeatLog,
});
__gen::record!(LangStringSet {});
__gen::record!(
    DataSpecificationIEC61360 { unit : __gen::EventGraph < __gen::List < char > >,
    source_of_definition : __gen::EventGraph < __gen::List < char > >, symbol :
    __gen::EventGraph < __gen::List < char > >, value_format : __gen::EventGraph <
    __gen::List < char > >, level_type : __gen::AWBagLog < LevelType >, preferred_name :
    __gen::ListLog < LangStringLog >, short_name : __gen::ListLog < LangStringLog >,
    definition : __gen::ListLog < LangStringLog >, value_list : __gen::ListLog <
    ValueReferencePairTypeLog >, }
);
__gen::record!(ValueReferencePairType {});
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum LevelType {
    #[default]
    Min,
    Max,
    Nom,
    Typ,
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum DataTypeIEC61360 {
    #[default]
    Date,
    String,
    StringTranslatable,
    IntegerMeasure,
    IntegerCount,
    IntegerCurrency,
    RealMeasure,
    RealCount,
    RealCurrency,
    Boolean,
    Url,
    Rational,
    RationalMeasure,
    Time,
    Timestamp,
}
__gen::record!(View {
    has_data_specification_feat: HasDataSpecificationFeatLog,
    referable_feat: ReferableFeatLog,
    has_semantics_feat: HasSemanticsFeatLog,
});
__gen::record!(
    MultiLanguageProperty { data_element_feat : DataElementFeatLog, value :
    __gen::ListLog < LangStringLog >, }
);
