// Auto-generated by Atraktos. Do not edit by hand.

mod __gen {
    pub use moirai_macros::record;
    pub use moirai_macros::union;
    pub use moirai_crdt::list::nested_list::ListLog;
    pub use moirai_protocol::state::event_graph::EventGraph;
    pub use moirai_crdt::list::eg_walker::List;
    pub use moirai_crdt::option::OptionLog;
}
__gen::record!(
    Root { behaviortrees : __gen::ListLog < BehaviorTreeLog >, main : BehaviorTreeLog, }
);
__gen::record!(
    BehaviorTree { id : __gen::EventGraph < __gen::List < char > >, child : Box <
    TreeNodeLog >, blackboard : BlackboardLog, }
);
__gen::union!(
    TreeNode = ExecutionNode(ExecutionNode, ExecutionNodeLog) | Decorator(Decorator,
    DecoratorLog) | ControlNode(ControlNode, ControlNodeLog) | SubTree(SubTree,
    SubTreeLog)
);
__gen::record!(
    TreeNodeFeat { id : __gen::EventGraph < __gen::List < char > >, name :
    __gen::OptionLog < __gen::EventGraph < __gen::List < char > >>, }
);
__gen::record!(Blackboard { entries : __gen::ListLog < BlackboardEntryLog >, });
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub enum Status {
    #[default]
    Running,
    Success,
    Failure,
}
__gen::union!(
    ExecutionNode = Action(Action, ActionLog) | Condition(Condition, ConditionLog)
);
__gen::record!(
    ExecutionNodeFeat { tree_node_feat : TreeNodeFeatLog, outflowports : __gen::ListLog <
    OutFlowPortLog >, inflowports : __gen::ListLog < InFlowPortLog >, }
);
__gen::union!(
    DataFlowPort = OutFlowPort(OutFlowPort, OutFlowPortLog) | InFlowPort(InFlowPort,
    InFlowPortLog)
);
__gen::record!(DataFlowPortFeat {});
__gen::record!(OutFlowPort { data_flow_port_feat : DataFlowPortFeatLog, });
__gen::record!(InFlowPort { data_flow_port_feat : DataFlowPortFeatLog, });
__gen::union!(Decorator = Inverter(Inverter, InverterLog));
__gen::record!(
    DecoratorFeat { tree_node_feat : TreeNodeFeatLog, child : Box < TreeNodeLog >, }
);
__gen::union!(
    ControlNode = Sequence(Sequence, SequenceLog) | Fallback(Fallback, FallbackLog)
);
__gen::record!(
    ControlNodeFeat { tree_node_feat : TreeNodeFeatLog, children : __gen::ListLog < Box <
    TreeNodeLog > >, }
);
__gen::record!(Sequence { control_node_feat : ControlNodeFeatLog, });
__gen::record!(Fallback { control_node_feat : ControlNodeFeatLog, });
__gen::union!(
    Action = OpenDoor(OpenDoor, OpenDoorLog) | EnterRoom(EnterRoom, EnterRoomLog) |
    CloseDoor(CloseDoor, CloseDoorLog)
);
__gen::record!(ActionFeat { execution_node_feat : ExecutionNodeFeatLog, });
__gen::union!(Condition = IsDoorOpen(IsDoorOpen, IsDoorOpenLog));
__gen::record!(ConditionFeat { execution_node_feat : ExecutionNodeFeatLog, });
__gen::record!(
    BlackboardEntry { key : __gen::EventGraph < __gen::List < char > >, value :
    __gen::EventGraph < __gen::List < char > >, }
);
__gen::record!(Inverter { decorator_feat : DecoratorFeatLog, });
__gen::record!(IsDoorOpen { condition_feat : ConditionFeatLog, });
__gen::record!(OpenDoor { action_feat : ActionFeatLog, });
__gen::record!(EnterRoom { action_feat : ActionFeatLog, });
__gen::record!(CloseDoor { action_feat : ActionFeatLog, });
__gen::record!(SubTree { tree_node_feat : TreeNodeFeatLog, tree : BehaviorTreeLog, });
