pub(crate) mod annotation;
pub mod classifier;
pub mod cycles;
mod datatype;
pub mod descriptor;
mod feature;
pub mod generate;
pub mod generator;
mod ident;
mod import;
mod operation;
pub mod package;
pub mod read_as_ecore;
pub mod reference;
pub mod semantics;
mod warnings;
