<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstract_inherits_concrete" nsURI="http://www.example.org/abstract_inherits_concrete" nsPrefix="abstract_inherits_concrete">
    <eClassifiers xsi:type="ecore:EClass" name="A">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//A" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="C" eSuperTypes="#//B">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
</ecore:EPackage>
