<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="http://www.example.org/test" nsPrefix="test">
    <eClassifiers xsi:type="ecore:EClass" name="Foo">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds0inf" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds1inf" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds01" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounds11" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="boundsninf" lowerBound="5" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="boundsnm" lowerBound="5" upperBound="10" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleList" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bag" ordered="false" unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="set" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bar">
        <eStructuralFeatures xsi:type="ecore:EReference" name="myFoo" eType="#//Foo"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="health" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="foo" lowerBound="1" eType="#//Foo"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Baz" eSuperTypes="#//Abstract"/>
</ecore:EPackage>
