use crate::{
    config::Config,
    error::{AtraktosError, Result},
};
use proc_macro2::TokenStream;
use quote::quote;
use std::{fs, path::Path};

/// Writes a complete Rust project for the generated code.
pub fn write_project(config: &Config, project_name: &str, code: &str) -> Result<()> {
    let project_name = sanitize_package_name(project_name);
    let root = &config.output_dir;
    let src_dir = root.join("src");

    fs::create_dir_all(&src_dir)?;

    let cargo_toml = render_cargo_toml(&project_name, &config.moirai_root)?;
    let main_rs = render_main_rs(&project_name);
    let generated_rs = render_generated_rs(code);

    fs::write(root.join("Cargo.toml"), cargo_toml)?;
    fs::write(src_dir.join("main.rs"), main_rs.to_string())?;
    fs::write(src_dir.join("generated.rs"), generated_rs)?;

    Ok(())
}

fn render_cargo_toml(project_name: &str, moirai_root: &Path) -> Result<String> {
    let moirai_root = fs::canonicalize(moirai_root)
        .map_err(|e| AtraktosError::Config(format!("Failed to resolve moirai root: {e}")))?;

    let moirai_crdt = moirai_root.join("moirai-crdt");
    let moirai_protocol = moirai_root.join("moirai-protocol");
    let moirai_macros = moirai_root.join("moirai-macros");

    Ok(format!(
        "[package]\nname = \"{project_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\nmoirai-crdt = {{ path = \"{}\" }}\nmoirai-protocol = {{ path = \"{}\" }}\nmoirai-macros = {{ path = \"{}\" }}\n",
        to_path_string(&moirai_crdt),
        to_path_string(&moirai_protocol),
        to_path_string(&moirai_macros)
    ))
}

fn render_main_rs(project_name: &str) -> TokenStream {
    quote! {
        mod generated;

        fn main() {
            println!("Generated CRDT project: {}", #project_name);
        }
    }
}

fn render_generated_rs(code: &str) -> String {
    let mut output = String::new();
    output.push_str("// Auto-generated by Atraktos. Do not edit by hand.\n\n");
    output.push_str(code);
    output
}

fn sanitize_package_name(name: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;

    for ch in name.chars() {
        let lower = ch.to_ascii_lowercase();
        let is_valid = lower.is_ascii_alphanumeric();

        if is_valid {
            out.push(lower);
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }

    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "generated-crdt".to_string()
    } else {
        trimmed
    }
}

fn to_path_string(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
